### ISSUE TITLE
Depends on old version of importlib_resources?

### ISSUE THREAD

**Issue by wolfv** [conda-forge/sphinx-book-theme-feedstock#16]
Hi folks,

we're using this theme in the `mamba-org` and I just noted that an old sphinx version gets installed on a M1 Apple computer.

The reason is that the `importlib_resources` dependency is quite constrained (and not available in that low version) on macos-arm64 I believe.

Is it necessary?

Referrring to https://github.com/conda-forge/sphinx-book-theme-feedstock/blob/7cc49d3bda035668118f986030efd919a541909f/recipe/meta.yaml#L29

**Comment by wolfv** [comment]
Current version is `5.x`

**Comment by bollwyvl** [comment]
yeah, that pin is taken directly from upstream... i guess we _could_ patch it etc...

https://github.com/executablebooks/sphinx-book-theme/blob/master/setup.py#L34

I guess my feeling is fixing/discussing it upstream would be preferable...
