### ISSUE TITLE
Why old version of pydata-sphinx-theme

### ISSUE THREAD

**Issue by erogluorhan** [conda-forge/sphinx-book-theme-feedstock#18]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Hi all,

The `pydata-sphinx-theme` dependency in the recipe is constrained  as follows:

`- pydata-sphinx-theme >=0.6.0,<0.7re`

`pydata-sphinx-theme` fixed significant bugs (e.g. Google analytics code snippet etc.) in their v0.7.0 and v0.7.1 recently, so this constraint in the recipe prevents us from taking advantage of those bug-fixes.

Is it necessary?

Thanks!

**Comment by bollwyvl** [comment]
This pin comes directly from the upstream:

https://github.com/executablebooks/sphinx-book-theme/blob/v0.1.6/setup.py#L35

Presumably the next upstream release will support (and be tested with) the
current version of pdst.

We typically try to avoid hacking dependency metadata unless it's causing
breakage/vulnerabilities.

**Comment by erogluorhan** [comment]
Ok, then, let me close this issue and open in the upstream for asking them if they are considering a release soon.
