### ISSUE TITLE
Meta.yaml for Version 0.1.10, doesnt appear to need importlib-resources

### ISSUE THREAD

**Issue by rxm7706** [conda-forge/sphinx-book-theme-feedstock#26]
https://github.com/executablebooks/sphinx-book-theme/blob/v0.1.10/setup.py
    python_requires=">=3.6",
    'importlib-resources>=3.0,<3.5; python_version < "3.7"',

https://github.com/conda-forge/sphinx-book-theme-feedstock/blob/56ed4e6a0f9128e0c6618cde4c570522867b0063/recipe/meta.yaml#L30
https://github.com/conda-forge/sphinx-book-theme-feedstock/blob/56ed4e6a0f9128e0c6618cde4c570522867b0063/recipe/meta.yaml#L28

Since the conda recipe is limiting the python version to >=3.7 the importlib-resources >=3.0,<3.5 is not needed, as it applies to only python 3.6

Effectively this forces an install of 'importlib-resources and an older version on Python >=3.7

We can either 
1) remove the importlib-resources, which appears to be the right solution since we saying python>=3.7 
   That seems to be what was done for version 0.2.0 - https://github.com/conda-forge/sphinx-book-theme-feedstock/commit/ec7157510a6b51666de5df723ecc2811a6276408

or we can try 

2) modify as - importlib-resources >=3.0,<3.5 # [py<37]
  Which I haven't tried before - but it might work

I can do a PR, if someone @conda-forge/jupyter-book can review and say which option is preferable. 
I'm learning towards option 1 

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - beautifulsoup4 >=4.6.1,<5
    - docutils >=0.15,<0.17
/*   - importlib-resources >=3.0,<3.5  # [py<37]   */
    - pydata-sphinx-theme >=0.7.2,<0.8
    - python >=3.7
    - pyyaml
    - sphinx >=3,<5

**Comment by bollwyvl** [comment]
is having that importlib-resources around actively breaking anything? they have been/continue to be a super hot mess, as they change faster than the stdlib for not a lot of value.

unforunately, we can't use selectors and keep `noarch: python` (which would lead to `{python x os x arch}` builds). we don't want to be in a situation where we're _knowingly_ creating situations where people can get bad solves if we can avoid it, even on older pythons that aren't strictly supported. but yes, if we did another build that raised the minimum python high enough to avoid the conditional dep, that would work.

**Comment by bollwyvl** [comment]
the [0.1.x](https://github.com/conda-forge/sphinx-book-theme-feedstock/tree/0.1.x) branch now exists for any related PRs

**Comment by rxm7706** [comment]
> is having that importlib-resources around actively breaking anything? they have been/continue to be a super hot mess, as they change faster than the stdlib for not a lot of value.

@bollwyvl thank you for looking at this. 
It's probably important only for a few cases, like we encounter where we have to rely on a large monolith conda env - and dependencies across 100's of packages. importlib dependency and versions locks give us a lot of pain. We are trying to do everything we can to get people to try and adopt jupyter-book - so I'm going through all the jupyter-book dependencies to see if we can make it all work. 

I have created a PR to 0.1.x branch https://github.com/conda-forge/sphinx-book-theme-feedstock/pull/27

**Comment by bollwyvl** [comment]
Welp, a lot of that comes from upstream pinning tightly... But we do what
we can here, I guess.

**Comment by bollwyvl** [comment]
closed by #27
