### ISSUE TITLE
Publishing v1.1.2 on conda-forge

### ISSUE THREAD

**Issue by matt-april** [conda-forge/sphinx-book-theme-feedstock#37]
### Comment:

It looks like there's a mismatch between what's on conda-forge (v1.1.1 https://anaconda.org/conda-forge/sphinx-book-theme) and what's on pypi (v1.1.2 https://pypi.org/project/sphinx-book-theme/#description).  Maybe the bot got confused from two versions being released on the same day?

Would it be possible to get v1.1.2 published on conda-forge as well?

**Comment by bollwyvl** [comment]
1.1.2 from #36 should be up within the half hour. Please re-open if there are further issues.
